name: build

on:
  push:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.1'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
